### ISSUE TITLE
nextflow.config or nextflow.config.example

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/GEMmaker#114]
As per the discussion on PR #107.  Here's the issue regarding if we should permanently move the `nextflow.config.example` file to be `nextflow.config`.   Here's my understanding of the Pro's and Con's.

Pro's
------
1. The end user doesn't have to remember to rename the file if they just want to test
2. The end user doesn't have to remember to rename the file if they customize it.

Con's.
-------
1.  As developers, we always have to be cognizant to restore the file back to its original state before committing changes. Otherwise, we can accidentally change defaults without realizing it.  This makes it especially problematic when we spot a problem while using real data and we want to fix it using the real data (not the example data).

**Comment by bentsherman** [comment]
Another pro (sort of) is that having a default `nextflow.config` seems to be pretty standard for many nextflow pipelines that I've seen.

For me this con is not a big one because it is a fairly common issue with projects such as these. You have some config file which has default settings but also has to be tweaked when you experiment with it. For example, all of our other nextflow pipelines (KINC-nf, gene-oracle-nf). But this problem doesn't go away simply by having `nextflow.config.example`. In fact, I would argue it gets worse -- you still have to transfer your changes from `nextflow.config` to `nextflow.config.example`, on top of filtering out the changes you don't want to commit. In my experience, managing the config file for GEMmaker has been much worse than for my other pipelines which use `nextflow.config`.

**Comment by bentsherman** [comment]
Another big pro is that having a default `nextflow.config` means that it's possible to run the workflow out of the box. For example you can do:
```
nextflow run rnatoy -with-docker
```

And nextflow will pull the pipeline, the docker images, and run the example provided by the pipeline. All in one command! No other preparation necessary except installing nextflow and Docker. I would like to be able to do the same thing for GEMmaker:
```
nextflow run systemsgenetics/GEMmaker -with-docker
```

But that will never work unless there is a default `nextflow.config`.

**Comment by spficklin** [comment]
Okay, you and @JohnHadish are starting to convince me.   Let's try it and see how it goes.
