### ISSUE TITLE
Non SRA names has 'Sample' prefix

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/GEMmaker#14]
When running GEMmaker with samples that are not from NCBI it seems that the sample names get a 'Sample_' prefix.  Is this a mistake I've made somewhere in the configuration or is this current behavior. If the latter can we remove the prefix?

**Comment by JohnHadish** [comment]
Worked on this issue this morning, it seems like it should be easy, but Nextflow is very adamant about not allowing input to be output in any process. 
Currently, the remote channels and local channels are mixed prior to the renaming of run ID to sample ID. This is done so that if the user has local [SDE]RR files that they will be merged into their respective [SDE]XX sample. 
Unfortunately, a side effect of this is that runs that are not in the format of [SDE]RR do not have anything to be renamed to. Since Nextflow refuses to allow input and output to be the same, these must be given an arbitrary name.
The best solution to this problem I have found is to have to add 2 additional steps. The first is before files are renamed and would basically check to see if files are in the format of [SDE]RR or not. If they are not, it would branch these files into another channel, and then bring them back in once the renaming and combining had reoccurred. I am not a big fan of this, because it would add another step where all files would have to wait at to be recombined into one channel, but we would be able to remove the "Sample_" from the head of the name.
I was wondering if this would be something that would be desirable.

**Comment by spficklin** [comment]
This may not be an issue as the ``create_GEM.py`` script strips off the 'Sample_` prefix.  So, let's close this for now.
