### ISSUE TITLE
failed_runs.metadata.txt in results directory

### ISSUE THREAD

**Issue by JohnHadish** [SystemsGenetics/GEMmaker#236]
The file `failed_runs.metadata.txt` is in the `results` directory, where as the final  `failed_runs.metadata.txt` is in the `reports` directory.

The `results` directory:
```
failed_runs.metadata.txt
GEMs
pipeline_info
reports
Samples
```
This may be confusing, as it is more or less human readable, but does not contain all of the failed runs:

Example of what is in the file:
```
{
    "SRR2931434": "Metadata was not returned by NCBI for this run."
}
```

Example of all runs that failed (in reports directory):

![image](https://user-images.githubusercontent.com/35115540/124802269-a07bc680-df0c-11eb-8b96-09c7a529fdbe.png)

**If a user is looking for what runs failed, the first file they encounter will not have all of the failed runs in it, but will be human readable, where as the actual file they want is burried deeper in directories and is not human readable.**

## Suggested fix
The files mentioned in the `failed _runs.metadata.txt` are also included in the final failed runs report. It would be better if the final report --`failed_runs.metadata.txt`-- was the only file available to the user.

It is also annoying that `failed_runs.metadata.txt` is an html report while the other is not. HTML reports are annoying to access on HPCs.

**Comment by spficklin** [comment]
The `failed_runs.metadata.txtfailed_runs.metadata.txt` will only have failures at the stage where metadata is retrieved about a sample.  That report gets created by a process that doesn't run in parallel so there's only one file.    Samples are downloaded separately and if they fail that generates a file with a `.failed_runs.download.txt.failed_runs.download.txt` suffix.   Also, if a sample fails to extract after download then a file with a `.failed_runs.fastq-dump.txt` is created.  The latter two files are found inside of the sample directories where as the first is found outside of the sample directories because it's from a single process.  The final failed run report combines the results from all of these types of failures.  

I think the only thing we should do here is to document what these files are.  Really the end user should ignore these unless they really want to do some scripting to deal with them.

**Comment by spficklin** [comment]
Fixed by recent PR
