### ISSUE TITLE
Use SRX IDs instead of SRR IDs as input

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/GEMmaker#31]
It seems like there is duplicate work going on between `SRA_splitter.py` and `retrieve_sample_metadata.py` -- you take a mapping of SRX to SRR IDs, split the SRR IDs, but then during the workflow you retrieve the original SRX for each SRR ID so that you can group the SRRs together properly. We should be able to either (1) provide the SRX ID with each SRR ID since we already have the mapping or (2) just use the SRX IDs as input and let the workflow retrieve the SRR IDs from NCBI. Both options seem better and feasible to me, (1) is nice because it doesn't involve a bunch of web queries. Any reasons why we can't do this?

**Comment by bentsherman** [comment]
There also appears to be some sort of bottleneck between SRR_to_sample_id and SRR_combine, because nextflow doesn't launch any SRR_combine processes until all SRR_to_sample_id processes are finished. I'd be willing to bet that providing the SRX ID's from the beginning would eliminate that bottleneck.

**Comment by cwytko** [comment]
The bottleneck is from the groupTuple call on the channel, it's blocking.
Right now I've been recommended to use groupKey call [See here](https://github.com/nextflow-io/nextflow/issues/796)

**Comment by spficklin** [comment]
One reason for leaving it as SRRs as input is the case where someone doesn't want to use all SRRs.  Not sure how common a case that is, but we can't support it if we don't allow SRRs as initial input.

**Comment by spficklin** [comment]
@cwytko can you provide an update here for the team on where this is at?

**Comment by spficklin** [comment]
After talking with Connor this morning.  We think it would be easiest long-term to have GEMmaker recieve a two column input file.  First column being the experiment (sample) ID and the second column being the run ID.  For local samples both column values on a single row would be the same.  

This will allow us to get around the horizontal running issue #40 .  And it will allow us to bulk download metadata later.

**Comment by spficklin** [comment]
So, this is now fixed in the master branch.  Nothing has changed with the original config inputs.  There are still separate configs for both local and remote files.  But now, there is a new script, `retreive_SRA_metadata.py`, and a new process that calls that script.  For remote files it bulk retrieves all metadata, collects the experiments and spits out the mapping of runs to experiments in a CSV format to stdout.  This CSV output gets put into a channel that gets parsed and groupTuple is run on that.  There is no more blocking because all data is available for the groupTuple
