### ISSUE TITLE
updates to the nextflow.config file

### ISSUE THREAD

**Issue by spficklin** [SystemsGenetics/GEMmaker#6]
In the profile section we should add a stub for each step in the workflow so that the user can easily custoimze it. Otherwise they have to do a lot of looking at the code to figure out the names of steps, etc. 

We should also change the Kamiak profile so the default number of hours is not 720.

**Comment by JohnHadish** [comment]
I will change the "Kamiak" to "slurm_cluster" as well

**Comment by JohnHadish** [comment]
I have changed this to try to make it more intuitive. There is now an "input" and an "output" section, as well as sections for the different processes that need them.  I chose to do this instead of trying to integrate these into a process, since they are used throughout the script.  I changed the commenting style to make it so the parameters are more viable to the eye. The format is that the overarching has the 
```
/**
 * Big concept
 */
``` 
style and the different parameter settings have 
```
// 
// Parameter documentation
//
```
 I think this makes it look nicer, as it was looking rather nasty when all were formatted the first way.

Comments on the order of the parameters and grouping are appreciated.

**Comment by JohnHadish** [comment]
A stub for each process has been added to the nextflow.config. Some are sparse, due to the fact that they are not customizable if we wish the workflow to be able to continue to the next step. We need to have standard outputs for the next step.
