### ISSUE TITLE
Miscellaneous updates to publishing options

### ISSUE THREAD

**Issue by bentsherman** [SystemsGenetics/GEMmaker#81]
- Need to add a `publish_sam` option, currently `publish_bam` is used to publish both SAM and BAM files.
- I guess we should add a `publish_raw` option? Now that we have this `prepDE.py` script generating raw counts which I assume is a third output format in addition to FPKM and TPM.
- The create GEM process should probably use the publish options to determine whether to create each GEM format.
- I guess we should add options for whether to run multiqc and createGEM.

**Comment by spficklin** [comment]
> Need to add a publish_sam option, currently publish_bam is used to publish both SAM and BAM files.

I don't think we would ever want to publish the SAM files. The BAM files are just binary version of the SAM file and users can always re-create the SAM files from the BAM files.  I think SAM files should always be cleaned up and never published.

> I guess we should add a publish_raw option? Now that we have this prepDE.py script generating raw counts which I assume is a third output format in addition to FPKM and TPM.

Yes, to be consistent we should have a `publish_raw` option.

> The create GEM process should probably use the publish options to determine whether to create each GEM format.

Yes the `createGEM` process should use those flags.  But it also uses the which_aligment too because only hisat2 generates FPKM even if the publish_fpkm flag is set to true.

> I guess we should add options for whether to run multiqc and createGEM.

I don't have an opinion on this.  I suppose if we default them to true.

**Comment by spficklin** [comment]
Should we clean these up before our v1.0 release?  If we can do them quickly I say yes.
